language: node_js
node_js:
  - 10

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user ./udagram-api-user/
  - docker tag udagram-api-user given8/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend/
  - docker tag udagram-frontend given8/udagram-frontend:v1
  - docker build -t reverseproxy ./reverseproxy/
  - docker tag reverseproxy given8/reverseproxy:v1
  - docker build -t udagram-api-feed ./udagram-api-feed/
  - docker tag udagram-api-feed given8/udagram-api-feed:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push given8/udagram-api-feed:v1
  - docker push given8/udagram-api-user:v1
  - docker push given8/udagram-frontend:v1
  - docker push given8/reverseproxy:v1
